### ISSUE TITLE
Not possible to publish to a non-Phusion PackageCloud repository

### ISSUE THREAD

**Issue by shaneog** [phusion/passenger_apt_automation#17]
The `phusion` name is prepended to all repositories passed in to the `publish` command.
This means third-party publishing isn't possible.

I'm not sure if this will be a `wont-fix` issue, but I thought it's worth raising.

**Comment by FooBarWidget** [comment]
Our publishing scripts aren't meant to be used by others. I imagine that if you are not Phusion, you probably wouldn't want to use PackageCloud anyway, but would rather use your own APT repository software. Our scripts already allow that. The `build` script outputs a bunch of regular Debian package files in the output directory, so that you can do whatever you want on them.
